capturd exception conserved
hazelcast/hazelcast-csharp-client pull request #542
Opened 2021-11-26 09:24 UTC by emreyigit

Captured exception is conserved in Hazelcast exception, and related warnings is added to description.

2021-12-01 15:33 UTC, zpqrtbnk requested changes
One small change proposal and then I am OK.

2021-12-01 15:33 UTC, zpqrtbnk commented on src/Hazelcast.Net/Clustering/MemberConnection.cs
> +        /// <remarks>After first connection is established, <b>TargetDisconnectedException</b> can be throwed. If connected member registers to cluster with different IP address apart from configured
```suggestion
        /// <remarks>After first connection is established, <b>TargetDisconnectedException</b> can be throwed. If
        // the connected member reports an IP address different from the configured one. In this case, connection 
        // will be switched, and an exception will be thrown.</remarks>
```

2021-12-01 15:57 UTC, zpqrtbnk approved these changes
All good.

2021-12-08 07:13 UTC, emreyigit commented on src/Hazelcast.Net.Tests/Sql/SqlQueryResultTests.cs
> +                var result = await Client.Sql.ExecuteQueryAsync($"SELECT * FROM {dummyMapName}");
I'm afraid I didn't get it. As long as I don't create mapping on server, I know that it throws `HazelcastSqlException`. If there is another type of exception occurring, that can fail the testing process in anyway.

2021-12-08 09:39 UTC, zpqrtbnk commented on src/Hazelcast.Net.Tests/Sql/SqlQueryResultTests.cs
> +                var result = await Client.Sql.ExecuteQueryAsync($"SELECT * FROM {dummyMapName}");
Think what Ihsan means is: you expect an exception, so you should test and ensure that an exception is indeed thrown. Here, if no exception is thrown, the test will pass, won't it? We have that:
```
var e = await AssertEx.ThrowsAsync(async () => result = await Client.Sql.ExecuteWhatever());
Assert.IsNotEmpty(e.Message);
```
If the code passes without throwing, `AssertEx` will throw a test exception. See?

2021-12-08 11:23 UTC, emreyigit commented on src/Hazelcast.Net.Tests/Sql/SqlQueryResultTests.cs
> +                var result = await Client.Sql.ExecuteQueryAsync($"SELECT * FROM {dummyMapName}");
@ihsandemir, test is improved.

2021-12-09 13:50 UTC, ihsandemir approved these changes

2021-12-09 13:50 UTC, ihsandemir commented on src/Hazelcast.Net/Clustering/MemberConnection.cs
> +        /// <remarks>After first connection is established, <b>TargetDisconnectedException</b> can be throwed. If
```suggestion
        /// <remarks>After first connection is established, <b>TargetDisconnectedException</b> may be thrown. If
```

2021-12-10 14:12 UTC, merged