Code cleanup + Copyright 2022
hazelcast/hazelcast-csharp-client pull request #622
Opened 2022-05-18 08:10 UTC by zpqrtbnk

This PR imports the tool that I have been using for cleaning up our code, and bumping the copyright year in C# files headers, and then updates all the files using this tool. It should make ZERO practical code changes, EXCLUSIVELY comments changes + remove a few `using` statements that were not required.

2022-07-22 13:56 UTC, emreyigit submitted a review, later dismissed

2022-07-25 16:03 UTC, srknzl requested changes
can you update all copyright years? As I see majority of them are not updated. example: src/Hazelcast.Net/Aggregation/AggregatorBase.cs

2022-07-26 15:17 UTC, zpqrtbnk commented
indeed, some files were apparently skipped, I have refreshed the PR - now it should be OK

2022-07-26 16:26 UTC, srknzl submitted a review, later dismissed

2022-07-29 09:05 UTC, emreyigit approved these changes

2022-08-02 14:21 UTC, srknzl approved these changes

2022-08-23 10:22 UTC, zpqrtbnk commented
merged master and now it wants to be approved again? force-merging.

2022-08-23 10:22 UTC, merged