Test Added for Retry Before Failover
hazelcast/hazelcast-csharp-client pull request #663
Opened 2022-07-13 13:38 UTC by emreyigit

A case is added to test that client is try to reconnect before doing a failover.

2022-07-18 13:00 UTC, srknzl commented on src/Hazelcast.Net.Tests/Clustering/FailoverTests.cs
> +            await AssertClusterA(map, RcClusterPrimary.Id);
The following is better I think. 

```suggestion
            await AssertClusterA(map, client.ClusterName);
```

2022-07-18 13:01 UTC, srknzl requested changes
Looks good except for one minor comment

2022-07-19 10:24 UTC, emreyigit commented on src/Hazelcast.Net.Tests/Clustering/FailoverTests.cs
> +            await AssertClusterA(map, RcClusterPrimary.Id);
Yeap, thanks.

2022-07-19 11:19 UTC, srknzl approved these changes

2022-07-25 09:59 UTC, zpqrtbnk approved these changes
approved

2022-07-25 10:01 UTC, merged