Upgrade to Csharp 10
hazelcast/hazelcast-csharp-client pull request #713
Opened 2022-08-31 13:35 UTC by emreyigit

No warnings occurred with the upgrade.

2022-09-01 09:37 UTC, zpqrtbnk requested changes
See comment.

2022-09-01 09:37 UTC, zpqrtbnk commented on src/Hazelcast.Net/Hazelcast.Net.csproj
> +  <PropertyGroup>
The default language version for all our projects is specified in `src/Directory.Build.Props` so I think you want to update that file, not any of the `.csproj` files. Other than that... if the PR triggers no new warning then it's all good.

2022-09-01 10:08 UTC, zpqrtbnk approved these changes
Approved.

2022-09-05 09:33 UTC, srknzl commented on src/Hazelcast.Net/AssemblySigning.cs
> +#pragma warning disable CA1305 // Specify IFormatProvider
Isn't this a warning?

2022-09-05 09:33 UTC, srknzl approved these changes
Approved but aren' there some warnings so you used pragma disables?

2022-09-06 09:53 UTC, merged

2022-09-06 09:54 UTC, emreyigit commented
@srknzl they can be neglectable ones. Also, those part are mostly in test helpers.